### ISSUE TITLE
关于站点刷流插件的同步种子刷流标签记功能支持transmission的需求

### ISSUE THREAD

**Issue by aicenluo** [InfinityPacer/MoviePilot-Plugins#1]
刷流插件非常好用。我的用法是通过qb刷流，同时对刷流的种子进行辅种，但是qb的问题是，辅种过程中校验的过程太过漫长，所以我想用tr刷流并辅种（tr的校验时间很短）
但是我把种子从qb转移到tr刷流的时候，插件不支持tr的刷流标签，导致没办法把从qb转移过去的刷流种子纳入刷流；并且我看开发计划中 自动分类管理 功能，也只支持qb。请问一下，是否这两个功能没办法适配tr，还是说并没有计划支持tr？

**Comment by InfinityPacer** [comment]
换了tranmission的webui，如果是 ronggang/transmission-web-control#640，那就是不支持
