### ISSUE TITLE
感谢大佬给plex制作插件，我这边找到几个好用的plex脚本，看看大佬能不能集成进MP里

### ISSUE THREAD

**Issue by Kev1nT** [InfinityPacer/MoviePilot-Plugins#1]
https://github.com/RemiRigal/Plex-Auto-Languages
一个选择语言音频则应用到整部剧的脚本，省去了每一集都要切换的麻烦

https://github.com/Bespertrijun/PrettyServer
可以为plex提供中文演员名称，可以和emby互相同步观看记录等

https://github.com/zfhxi/PlexMusicScanner-Mod
可以让plex音乐库支持更多的格式

大佬看看这些哪个能集成到MP里，感谢

**Comment by InfinityPacer** [comment]
Plex中文演员的，这个有测试过吗，我之前研究，Plex界面会强制使用在线元数据，即便修改了本地元数据，也是显示不出来的。

**Comment by Kev1nT** [comment]
> Plex中文演员的，这个有测试过吗，我之前研究，Plex界面会强制使用在线元数据，即便修改了本地元数据，也是显示不出来的。

测试过是可以的，不过会存在一部分是中文演员，剩下几个英文的问题
并且只是短期测试，后面重装NAS我就把那个docker关了

**Comment by Kev1nT** [comment]
https://www.zhihu.com/question/582024052/answer/2875053828
另外，知乎上也有位大佬对Plex颇有研究，他分享了很多的工具和玩法，您也可以看看

**Comment by InfinityPacer** [comment]
中文演员这个，有时间可以帮忙确认下，你提供的那个仓库，也是类似更新Plex本地元数据的方案，按我之前测试，Plex默认取在线元数据，除非阻断在线元数据的请求，否则无法显示中文演员，我是用网页端测试的，所以一直没有改演员削刮的插件。

**Comment by InfinityPacer** [comment]
自动音轨的后续可以集成，音乐的这个插件不大适合，有需要可以自行根据作者说明集成。

**Comment by InfinityPacer** [comment]
已新增Plex演职人员刮削插件
