### ISSUE TITLE
[featureRequest] `Plex中文本地化`增量更新

### ISSUE THREAD

**Issue by BrettDean** [InfinityPacer/MoviePilot-Plugins#10]
想要让`Plex中文本地化`的`入库后执行一次`只更新对应的入库内容，而不是全部更新，我这里每隔一小段时间就会入库一个新的内容，每次都全量更新没必要

要是可以入库的时候增量更新，然后定期全量更新一次就好了

`锁定元数据：False`

**Comment by BrettDean** [comment]
```
【INFO】2024-06-04 11:13:57,544 - plexlocalization - 运行完毕，用时 723.8186440467834 秒
```
700秒其实也还行，就是打开`入库后执行一次`的话，一天24小时都会不断刷新。。

**Comment by InfinityPacer** [comment]
这个插件要整体重构

**Comment by BrettDean** [comment]
> 这个插件要整体重构

那太麻烦了😂
没事，我就cron定时运行也够了，`入库后执行一次`不要问题也不大

**Comment by InfinityPacer** [comment]
不会，这个插件本来就准备整体重构，只是最近还没有时间处理
