### ISSUE TITLE
为什么备份用不了，好像是文件没生成

### ISSUE THREAD

**Issue by windyhun** [InfinityPacer/MoviePilot-Plugins#10]
【INFO】2024-05-13 06:17:27,818 - webdavbackup - 备份失败，请排查日志
【INFO】2024-05-13 06:17:27,817 - webdavbackup - 清理本地临时文件：/config/MoviePilot-Backup-2024-05-13_06-17-27.zip
【ERROR】2024-05-13 06:17:27,816 - webdavbackup - 上传到WebDAV服务器失败: Remote resource: /MoviePilot-Backup-2024-05-13_06-17-27.zip not found
【INFO】2024-05-13 06:17:27,813 - webdavbackup - 远程备份路径为：http://xxxxxxxx/dav/MoviePilot-Backup-2024-05-13_06-17-27.zip
【INFO】2024-05-13 06:17:27,812 - webdavbackup - 清理本地临时文件夹：/config/MoviePilot-Backup-2024-05-13_06-17-27
【INFO】2024-05-13 06:17:27,812 - webdavbackup - 成功创建ZIP备份文件: /config/MoviePilot-Backup-2024-05-13_06-17-27.zip
【INFO】2024-05-13 06:17:27,800 - webdavbackup - 正在压缩备份文件: /config/MoviePilot-Backup-2024-05-13_06-17-27.zip
【INFO】2024-05-13 06:17:27,798 - webdavbackup - 正在备份文件: /config/category.yaml
【INFO】2024-05-13 06:17:27,798 - webdavbackup - 正在备份文件: /config/app.env
【INFO】2024-05-13 06:17:27,797 - webdavbackup - 正在备份文件: /config/user.db
【INFO】2024-05-13 06:17:27,796 - webdavbackup - 本地临时备份文件夹路径：/config/MoviePilot-Backup-2024-05-13_06-17-27
【INFO】2024-05-13 06:17:27,795 - webdavbackup - 成功连接到WebDAV服务器
【INFO】2024-05-13 06:17:27,787 - webdavbackup - 开始执行WebDAV备份

**Comment by InfinityPacer** [comment]
@windyhun 检查服务器地址是否正确

**Comment by InfinityPacer** [comment]
如与 #14 类似的问题，可更新后重试
