### ISSUE TITLE
刷流插件同时下载任务数不灵什么情况

### ISSUE THREAD

**Issue by 389377616** [InfinityPacer/MoviePilot-Plugins#12]
我设置的是3，我发现下载器里还有两个任务没有完成，刷流插件哐哐一下给我增加进去六七个个下载任务
![222](https://github.com/InfinityPacer/MoviePilot-Plugins/assets/52220248/832ef839-60a9-4193-abde-37b1c7abe8a1)
![333](https://github.com/InfinityPacer/MoviePilot-Plugins/assets/52220248/418274b0-469a-46a9-a71e-0a212702bc17)

**Comment by InfinityPacer** [comment]
qb无法重现，建议打开更多日志自行排查。

**Comment by 389377616** [comment]
> qb无法重现，建议打开更多日志自行排查。

我使用的下载器是tr

**Comment by InfinityPacer** [comment]
建议使用qb
