### ISSUE TITLE
刷流能否支持打上片名的标签

### ISSUE THREAD

**Issue by zhang05lei20** [InfinityPacer/MoviePilot-Plugins#13]
如题，能否支持刷流打上片名，和mp上下载影片一样，主要是为了筛选刷流任务中有哪些是需要的资源，可以转移目录并刮削他（刷流目录设置的默认不刮削），因为种子的名称可能第一时间无非分辨。
![image](https://github.com/InfinityPacer/MoviePilot-Plugins/assets/42257419/7d9950a1-eecd-464b-936b-7528948455b3)

**Comment by InfinityPacer** [comment]
@zhang05lei20 使用刷流种子整理插件，以及刷流低频版数据页支持子标题显示

**Comment by zhang05lei20** [comment]
这个插件貌似无法满足

**Comment by InfinityPacer** [comment]
@zhang05lei20 不大清楚你的具体场景，用这个插件整理就能看到相关的子标题内容
