### ISSUE TITLE
站点刷流（低频版）

### ISSUE THREAD

**Issue by glfdxh** [InfinityPacer/MoviePilot-Plugins#14]
站点刷流（低频版）

报告老师：

1.想要在选种规则里能选上传人数和下载人数的比例的选项。

2.下载下来的种子在做种期间显示477800小时的做种数，与删种规则冲突，导致一下载下来被删了。人在海外，能问能否优化一下因时区不同导致的现象。

3.选种时出现“负六百九十小时发的种子”，但是“发布时间”选项里无法选择负数的时间。同样是人在海外导致的。

**Comment by InfinityPacer** [comment]
信息太少，无法评估你的需求

**Comment by glfdxh** [comment]
<img width="1279" alt="截屏2024-06-08 14 54 53" src="https://github.com/InfinityPacer/MoviePilot-Plugins/assets/157491224/723dc49b-7469-4dd8-bf0c-11b8aaa1658a">
<img width="1510" alt="截屏2024-06-08 14 57 22" src="https://github.com/InfinityPacer/MoviePilot-Plugins/assets/157491224/b78572f2-e3ec-41fd-9a9f-0821587f73e4">

报告老师，这是我前面第二第三问题的补充，请问这是我自己设置好的问题吗，前面的时间是我所在地的准确时间，与国内有12小时的时差，国内比我这块12小时

**Comment by InfinityPacer** [comment]
- 做种时间，是QB接口返回的，可以尝试把删除条件拿掉，看下QB实际的做种时间是多少
- 发布时间，首先你需要看下2024-06-08 23:38:02 这个时间是否是一个正确的时间，是UTC+8的时间，还是你的当地时间，日志记录的时间为 2024-06-08 13:46:55 ，这个是否为你的当地时间
- 最后，需要确认你的容器的时区时间是多少，MoviePilot的docker镜像默认TZ应该是Asia/Shanghai，是否有调整

**Comment by glfdxh** [comment]
报告老师：

1.问题二（解决）：

根据老师提示后修改时区发现unraid应用商店里拉取的qb有内置时区为纽约且无法更改，手动再添加一个时区也不生效。从新从dockerhub上拉取新的qb且正确添加我所在的时区(Canada/Eastern)后，不会出现“做种时间”是四十多万小时的现象。。

问题二解决，谢谢老师。

2.问题三：

(1):根据老师提示后修改时区发现我mp有内置时区为“纽约”且无法更改 但日志所显示时间为我所在地时间(Canada/Eastern)。

(2):手动添加我所在的时区(Canada/Eastern)后 日志时间反而变得错误。
      
      以上两个时区都会显示种子发布时间为负数。

(3)将时区修改为“Asia/Shanghai”后，日志时间变回国内，“发布时间”为负数的问题也消失。

--但如果我想要用回我的本地时间(Canada/Eastern),我能不能通过什么设置来规避插件显示的负数的“发布时间”，插件里面“发布时间”无法设置成负数--

**Comment by InfinityPacer** [comment]
- 一个正常设计的程序，时区都是跟随环境变量走的，也就是docker中配置的TZ，都是根据程序的时区去计算发布时间，那如你所说，大概率就是负数了。
- 如果你用国内的站点，站点时区基本上都是UTC+8的，程序不大可能主动去适配这种站点的逻辑，在刷流的README中，有提到时区的调整问题，建议你还是切回Asia/Shanghai 来使用
- 最后，如果却有必要，下个版本可以调整，但不确定是否能解决你的问题

**Comment by InfinityPacer** [comment]
此外，针对你提的第一点，想要在选种规则里能选上传人数和下载人数的比例的选项。
这个问题，之前已经答复过，站点的上传人数和下载人数是不准确的，该配置项没有参考意义。

**Comment by glfdxh** [comment]
> 此外，针对你提的第一点，想要在选种规则里能选上上传人数和下载人数的比例的选项。这个问题，之前已经答复过，站点的上传人数和下载人数是不准确的，该配置项没有参考意义。
感谢老师的详细回复，我清楚了。现在把mp时区换回国内，qb时区换成当地后 所有功能都能正常使用了，麻烦老师了。
