### ISSUE TITLE
一有新文件入库，系统通知就会发两条错误信息

### ISSUE THREAD

**Issue by behinder85** [InfinityPacer/MoviePilot-Plugins#16]
![image](https://github.com/InfinityPacer/MoviePilot-Plugins/assets/60542924/446f2b39-e7a1-433b-ba76-070ebbfd4ac8)

不知是何原因

插件版本V1.0
MP版本V1.9.6

**Comment by InfinityPacer** [comment]
这个是主程序触发的事件，打开MoviePilot Web页面，在系统提醒中应该也能找到对应的错误，可以找到对应日志，反馈至[MoviePilot](https://github.com/jxxghp/MoviePilot/issues/new/choose)

**Comment by behinder85** [comment]
> 这个是主程序触发的事件，打开MoviePilot Web页面，在系统提醒中应该也能找到对应的错误，可以找到对应日志，反馈至[MoviePilot](https://github.com/jxxghp/MoviePilot/issues/new/choose)

好的好的，我转过去反馈一下
