### ISSUE TITLE
刷流插件添加任务标签的时候有时候会有几乱码标签，这个是什么情况？

### ISSUE THREAD

**Issue by 389377616** [InfinityPacer/MoviePilot-Plugins#17]
![微信截图_20240619233540](https://github.com/InfinityPacer/MoviePilot-Plugins/assets/52220248/0dc2a34a-f03e-4a23-a16f-ffc9a87861c2)

**Comment by 389377616** [comment]
这个乱码是有啥特殊作不成，有了这个标签一栏看着有点乱

**Comment by InfinityPacer** [comment]
请查看插件README

**Comment by 389377616** [comment]
> 请查看插件README

刷流任务结束删除任务的时候没法同时删除这个标签嘛，只能自己手动清理嘛
