### ISSUE TITLE
【种子关键字分类整理】I佬提个问题，不知道是bug还是就这么设计的

### ISSUE THREAD

**Issue by kanekicany** [InfinityPacer/MoviePilot-Plugins#20]
【种子关键字分类整理】

- torrent_filter:
    torrent_title: ''
    torrent_category: ''
    torrent_tags:
      - '刷流'
  torrent_target:
    change_directory: ''
    change_category: ''
    add_tags:
      - 'BRUSH'
    remove_tags:
      - '已整理'
    auto_category: false

- torrent_filter:
    torrent_tags:
      - '彩虹岛'
  torrent_target:
    add_tags:
      - 'SITE:彩虹岛'
    remove_tags:
      - '彩虹岛'
    auto_category: false

- torrent_filter:
    torrent_tags:
      - '观众'
  torrent_target:
    add_tags:
      - 'SITE:观众'
    remove_tags:
      - '观众'
    auto_category: false

同时包含了以上多个标签的，符合第一个条件整理后，即使符合后面的条件也不会匹配上了，希望多条件不要短路。（配置这么写是想要给标签排个序）

**Comment by InfinityPacer** [comment]
目前是满足一组规则后就跳出处理

**Comment by kanekicany** [comment]
> 目前是满足一组规则后就跳出处理

嗯，只是我这么个写法有个问题就是”刷流“不删每次都满足条件，删了的话刷流插件的下载器监控就没法用了。如果不管下载器监控这个功能，第一次匹配到第一组后跳出了也无所谓，因为下一次就能执行到下面一组规则了。

**Comment by InfinityPacer** [comment]
a13dc554d3095db3c6f25dd9a532637c843c137e 已支持
