### ISSUE TITLE
ip大佬，一条硬链接报错问题

### ISSUE THREAD

**Issue by cng10001** [InfinityPacer/MoviePilot-Plugins#22]
诊断插件检查了一下发现有这样一条报错 但是我在历史记录具体看了后没发现啥问题啊
![image](https://github.com/InfinityPacer/MoviePilot-Plugins/assets/115156545/50202b6c-8a36-4a8e-8566-694f0b30c9d4)
根目录能对上 应该就没问题吧？
![image](https://github.com/InfinityPacer/MoviePilot-Plugins/assets/115156545/9482e5e4-f8a2-4575-b65d-1b3a15b3703d)

**Comment by InfinityPacer** [comment]
如果不是smb映射挂载，一般是同版本覆盖导致，可通过ls -i查看，也可尝试重新整理看下。

**Comment by cng10001** [comment]
6 同版本覆盖了
