### ISSUE TITLE
Plex演职人员刮削 豆瓣失败限频

### ISSUE THREAD

**Issue by loongcheung** [InfinityPacer/MoviePilot-Plugins#23]
【WARNING】2024-06-28 23:33:39,038 - douban - 触发豆瓣API速率限制，错误信息：{'msg': 'search_access_rate_limit', 'code': 1080, 'request': 'GET /v2/search/weixin', 'localized_message': '搜索访问太频繁'} ...

【WARNING】2024-06-28 07:59:57,797 - douban - 触发豆瓣IP速率限制，错误信息：{'msg': 'subject_ip_rate_limit', 'code': 1309, 'request': 'GET /v2/movie/36093351', 'localized_message': '您所在的网络存在异常，请登录后重试。'} ...

这种能否通过设置豆瓣 cookie 解决

**Comment by InfinityPacer** [comment]
豆瓣严格控制存量api调用，可考虑取消元数据锁定。

**Comment by loongcheung** [comment]
之前开启过元数据锁定，再次取消是不是就不生效了，之前都锁定过了

**Comment by InfinityPacer** [comment]
Plex元数据锁定相关信息请咨询Plex官方客服
