### ISSUE TITLE
刷流插件不支持青蛙和rousi

### ISSUE THREAD

**Issue by hhb1994** [InfinityPacer/MoviePilot-Plugins#27]
如题,在日志中看到能查询到结果,但是在下载器(tr)中没有触发下载任务,试了其他站点(馒头,织梦)是ok的
![image](https://github.com/InfinityPacer/MoviePilot-Plugins/assets/26303844/bec7df93-46e9-46d3-8506-d20a205e07db)

**Comment by InfinityPacer** [comment]
请查README

**Comment by hhb1994** [comment]
https://github.com/jxxghp/MoviePilot/issues/1809
已解决 是因为新入站,没有手动下载过一次种子
感谢大佬
