### ISSUE TITLE
Plex中文本地化插件自动停止

### ISSUE THREAD

**Issue by bainw2023** [InfinityPacer/MoviePilot-Plugins#29]
plex中文本地化插件无法安装使用，会自动停止，且已安装界面未显示插件。Moviepilot版本为1.9.11
![微信图片编辑_20240715164934](https://github.com/user-attachments/assets/5be48808-9201-4364-89db-2a6ce005d962)

**Comment by InfinityPacer** [comment]
常见于首次安装插件或重建容器，请检查依赖是否已安装，如未安装，可尝试自行安装再进行插件安装，相关命令参考
- 安装PlexLocalization依赖
```
pip install pypinyin~=0.51.0
```
- 遍历安装所有插件依赖
```
find /app/app/plugins -name requirements.txt -exec pip install -r {} \;
```
