### ISSUE TITLE
插件市场只显示飞书机器人消息通知插件

### ISSUE THREAD

**Issue by anooki-c** [InfinityPacer/MoviePilot-Plugins#3]
大佬，我看mp已经默认集成了你的插件库
但是我在mp上插件市场里勾选作者，只能显示飞书机器人这个插件，plex相关的都没有是什么原因
mp版本：1.9.0
![image](https://github.com/InfinityPacer/MoviePilot-Plugins/assets/55230532/d88d4a51-5932-45fb-a554-6b366a86d2b1)

日志关于插件有报错，提示获取0个第三方插件，实际mp插件市场里有很多插件
![image](https://github.com/InfinityPacer/MoviePilot-Plugins/assets/55230532/c9c041be-c379-43f2-bb25-ada8c2bb2c14)

`WARNING: plugin.py - 获取插件库失败：https://github.com/jxxghp/MoviePilot-Plugins
https://github.com/InfinityPacer/MoviePilot-Plugins
https://github.com/thsrite/MoviePilot-Plugins
https://github.com/honue/MoviePilot-Plugins
https://github.com/dandkong/MoviePilot-Plugins
https://github.com/Aqr-K/MoviePilot-Plugins
https://github.com/AnjoyLi/MoviePilot-Plugins
https://github.com/WithdewHua/MoviePilot-Plugins
https://github.com/HankunYu/MoviePilot-Plugins
https://github.com/baozaodetudou/MoviePilot-Plugins
https://github.com/almus2zhang/MoviePilot-Plugins
INFO:    plugin.py - 共获取到 0 个第三方插件
`

**Comment by InfinityPacer** [comment]
- 确认你的环境可以访问github
- 配置github_token

**Comment by anooki-c** [comment]
> * 确认你的环境可以访问github
可以访问的，我在路由器里ping了，都是正常
![image](https://github.com/InfinityPacer/MoviePilot-Plugins/assets/55230532/200d4630-b8f1-4614-bb3d-1f9219ffdfe2)

> * 配置github_token
已经配置了，设置了永久有效，所有权限都勾选了
![image](https://github.com/InfinityPacer/MoviePilot-Plugins/assets/55230532/c8e32266-dc25-4a3b-83e5-3dff5e63bacf)

**Comment by InfinityPacer** [comment]
你的第三方插件变量配错了，多个地址使用,分隔，不要换行。
```
PLUGIN_MARKET=https://github.com/jxxghp/MoviePilot-Plugins,https://github.com/InfinityPacer/MoviePilot-Plugins
```

**Comment by anooki-c** [comment]
> 你的第三方插件变量配错了，多个地址使用,分隔，不要换行。
> 
> ```
> PLUGIN_MARKET=https://github.com/jxxghp/MoviePilot-Plugins,https://github.com/InfinityPacer/MoviePilot-Plugins
> ```

可以了，感谢大佬，改过来大部分都可以了，只有几个插件库还是无法加载，估计是网络问题

**Comment by anooki-c** [comment]
> 你的第三方插件变量配错了，多个地址使用,分隔，不要换行。
> 
> ```
> PLUGIN_MARKET=https://github.com/jxxghp/MoviePilot-Plugins,https://github.com/InfinityPacer/MoviePilot-Plugins
> ```

可以了，感谢大佬，改过来大部分都可以了，只有几个插件库还是无法加载，估计是网络问题
