### ISSUE TITLE
刷流插件个别种子大小识别为0

### ISSUE THREAD

**Issue by AboutCXJ** [InfinityPacer/MoviePilot-Plugins#30]
version:v3.3

选种里 种子大小设置了 从0开始

<img width="1256" alt="截屏2024-07-15 20 40 57" src="https://github.com/user-attachments/assets/66600818-c258-437d-b641-5c86119ffa68">
<img width="1067" alt="截屏2024-07-15 20 45 18" src="https://github.com/user-attachments/assets/a443cd58-14b9-441c-b8c9-9a0ca01d67f7">

**Comment by InfinityPacer** [comment]
请参考[README](https://github.com/InfinityPacer/MoviePilot-Plugins/blob/main/plugins/brushflowlowfreq/README.md#faq)
