### ISSUE TITLE
刷流插件报错

### ISSUE THREAD

**Issue by MrLi1982** [InfinityPacer/MoviePilot-Plugins#31]
![46504b9987c84021e9dfc348f9c0a03d](https://github.com/user-attachments/assets/e59e9897-0542-4097-86fc-2e4273439ffc)
一直在报这个错误，请大神指教，如何处理！！

**Comment by InfinityPacer** [comment]
有效信息太少，无法定位问题

**Comment by lindaiyu99** [comment]
设定-连接-下载器 qB或Tr，确认地址、用户名、密码是否正确，用ipv4地址。
