### ISSUE TITLE
最新版刷流插件bug（同时下载任务数检查问题）

### ISSUE THREAD

**Issue by ShawsFOR** [InfinityPacer/MoviePilot-Plugins#34]
我安装了最新版刷流插件，遇到如下问题。
当我设置同时下载任务数为3时，遇到两种情况：
第一种，同时加入了3个同一个站点种子的下载任务，会把三个下载任务都暂停；
第二种，陆续加入不同站点种子的下载任务，会把第三个任务暂停。
而且，如果我手动开始，在下一次检查时，如果还是3个任务在下载，会再把第三个任务暂停

**Comment by InfinityPacer** [comment]
用强制重装插件，强制重装一次
