### ISSUE TITLE
站点刷流Brush服务 执行失败

### ISSUE THREAD

**Issue by ZACKLZ** [InfinityPacer/MoviePilot-Plugins#38]
mp自动执行时会提示以下报错，但看刷流插件的日志时，又是正常运行中

【站点刷流Brush服务 执行失败】
object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/app/app/scheduler.py", line 374, in start
    job["func"](*args, **kwargs)
  File "/app/app/plugins/brushflow/__init__.py", line 1967, in brush
    pre_condition_passed, reason = self.__evaluate_pre_conditions_for_brush()
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/plugins/brushflow/__init__.py", line 2193, in __evaluate_pre_conditions_for_brush
    if config_value and check(config_value):
                        ^^^^^^^^^^^^^^^^^^^
  File "/app/app/plugins/brushflow/__init__.py", line 2172, in <lambda>
    ("maxdlcount", lambda config: self.__get_downloading_count() >= int(config),
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/plugins/brushflow/__init__.py", line 3649, in __get_downloading_count
    return len(torrents) or 0
           ^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()

![image](https://github.com/user-attachments/assets/5fe981bd-5d21-459f-b2c7-01cd1856e5a9)

**Comment by InfinityPacer** [comment]
请提供对应时间段完整的MP日志文件

**Comment by ZACKLZ** [comment]
> 请提供对应时间段完整的MP日志文件

【INFO】2024-08-08 19:41:32,907 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-08-08 19:41:32,281 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-08-08 19:38:56,526 - doh.py - 已解析 [webservice.fanart.tv] 为 [51.89.210.79] (缓存)
【INFO】2024-08-08 19:38:45,413 - command.py - 处理事件：notice.message - [<function Discord.send at 0x7f6f25992840>]
【INFO】2024-08-08 19:38:45,363 - command.py - 处理事件：system.error - [<function AutoDiagnosis.handle_error_event at 0x7f6f242f7ec0>, <function SystemNotification.notification at 0x7f6f24b93740>]

TypeError: object of type 'NoneType' has no len()
           ^^^^^^^^^^^^^
    return len(torrents) or 0
  File "/app/app/plugins/brushflow/__init__.py", line 3649, in __get_downloading_count
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ("maxdlcount", lambda config: self.__get_downloading_count() >= int(config),
  File "/app/app/plugins/brushflow/__init__.py", line 2172, in <lambda>
                        ^^^^^^^^^^^^^^^^^^^
    if config_value and check(config_value):
  File "/app/app/plugins/brushflow/__init__.py", line 2193, in __evaluate_pre_conditions_for_brush
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    pre_condition_passed, reason = self.__evaluate_pre_conditions_for_brush(include_network_conditions=False)
  File "/app/app/plugins/brushflow/__init__.py", line 2043, in __brush_site_torrents
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    if not self.__brush_site_torrents(siteid=site.id, torrent_tasks=torrent_tasks,
  File "/app/app/plugins/brushflow/__init__.py", line 1994, in brush
    job["func"](*args, **kwargs)
  File "/app/app/scheduler.py", line 374, in start
【ERROR】2024-08-08 19:38:45,356 - scheduler.py - 定时任务 站点刷流Brush服务 执行失败：object of type 'NoneType' has no len() - Traceback (most recent call last):
【INFO】2024-08-08 19:37:18,278 - indexer - 憨憨 搜索完成，耗时 7 秒，返回数据：100
【INFO】2024-08-08 19:37:10,660 - spider.py - 开始请求：https://hhanclub.top/torrents.php
【INFO】2024-08-08 19:37:10,627 - torrents.py - 开始获取站点 hhanclub.top 最新种子 ...
【INFO】2024-08-08 19:36:33,254 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-08-08 19:36:32,284 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-08-08 19:31:33,338 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-08-08 19:31:32,280 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-08-08 19:26:47,924 - doh.py - 已解析 [webservice.fanart.tv] 为 [51.89.210.79] (缓存)
【INFO】2024-08-08 19:26:36,775 - command.py - 处理事件：notice.message - [<function Discord.send at 0x7f6f25992840>]
【INFO】2024-08-08 19:26:36,739 - command.py - 处理事件：system.error - [<function AutoDiagnosis.handle_error_event at 0x7f6f242f7ec0>, <function SystemNotification.notification at 0x7f6f24b93740>]

TypeError: object of type 'NoneType' has no len()
           ^^^^^^^^^^^^^
    return len(torrents) or 0
  File "/app/app/plugins/brushflow/__init__.py", line 3649, in __get_downloading_count
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ("maxdlcount", lambda config: self.__get_downloading_count() >= int(config),
  File "/app/app/plugins/brushflow/__init__.py", line 2172, in <lambda>
                        ^^^^^^^^^^^^^^^^^^^
    if config_value and check(config_value):
  File "/app/app/plugins/brushflow/__init__.py", line 2193, in __evaluate_pre_conditions_for_brush
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    pre_condition_passed, reason = self.__evaluate_pre_conditions_for_brush()
  File "/app/app/plugins/brushflow/__init__.py", line 1967, in brush
    job["func"](*args, **kwargs)
  File "/app/app/scheduler.py", line 374, in start
【ERROR】2024-08-08 19:26:36,723 - scheduler.py - 定时任务 站点刷流Brush服务 执行失败：object of type 'NoneType' has no len() - Traceback (most recent call last):
【INFO】2024-08-08 19:26:33,469 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-08-08 19:26:32,284 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-08-08 19:21:33,160 - transfer.py - 没有获取到已完成的下载任务

**Comment by ZACKLZ** [comment]
额，还需要提供啥吗

**Comment by InfinityPacer** [comment]
> 额，还需要提供啥吗

不需要了

**Comment by ZACKLZ** [comment]
> > 额，还需要提供啥吗
> 
> 不需要了

大佬已经修复了？
