### ISSUE TITLE
站点刷流低频版的小建议

### ISSUE THREAD

**Issue by Vivitoto** [InfinityPacer/MoviePilot-Plugins#39]
大佬好，站点刷流低频版插件，可否考虑增加以下功能？
1.限制站点每小时进种数量，针对站点对每小时种子下载数有限制，可以考虑在站点独立配置中增加以适应分站点的不同情况
2.将保种体积限制优先级进行提高，我现在使用的是站点独立配置，但在这个情况下就没有办法对保种体积上限进行设置，导致硬盘满了之后还在进种
以上两点作为小小的建议，大佬闲暇之余可以进行考虑～

**Comment by InfinityPacer** [comment]
- 限制站点每小时进种数量，可以考虑关闭「站点顺序刷流」，长期来看是平均每个站点刷流
- 保种体积限制优先级进行提高，「保种体积」目前为全局配置，总体积达标后会停止刷流，详细信息参考 [README](https://github.com/InfinityPacer/MoviePilot-Plugins/blob/main/plugins/brushflowlowfreq/README.md)
