### ISSUE TITLE
选择多个站点时，只会刷一个站点

### ISSUE THREAD

**Issue by blackappleD** [InfinityPacer/MoviePilot-Plugins#50]
大概半个月时间，都只刷了冰淇淋，没有刷CAR
![image](https://github.com/user-attachments/assets/5dfb713b-a803-4e36-81c9-ffb0209f4e3b)
![image](https://github.com/user-attachments/assets/d090746d-2277-40c5-bc59-f8b3f6581773)

**Comment by blackappleD** [comment]
> 大概半个月时间，都只刷了冰淇淋，没有刷CAR ![image](https://private-user-images.githubusercontent.com/36764324/371834837-5dfb713b-a803-4e36-81c9-ffb0209f4e3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1OTUxOTMsIm5iZiI6MTcyNzU5NDg5MywicGF0aCI6Ii8zNjc2NDMyNC8zNzE4MzQ4MzctNWRmYjcxM2ItYTgwMy00ZTM2LTgxYzktZmZiMDIwOWY0ZTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDA3MjgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwODZkMzcwMjNiZmU0NTJkYWMyMWE3NDVkYTllNDgwN2I1NTBjNTM5MmU4ZjNhY2FmMTVlMzIyNGYxYjIyNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bltOpGz9wn9AJeOxsb-6SzmOSVbQUUkSmfxjB_oySB4) ![image](https://private-user-images.githubusercontent.com/36764324/371834866-d090746d-2277-40c5-bc59-f8b3f6581773.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1OTUxOTMsIm5iZiI6MTcyNzU5NDg5MywicGF0aCI6Ii8zNjc2NDMyNC8zNzE4MzQ4NjYtZDA5MDc0NmQtMjI3Ny00MGM1LWJjNTktZjhiM2Y2NTgxNzczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDA3MjgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0NzAwYmI4YzM3ZDYyNWI3ZmE5M2NjN2ZlY2Q1ZDQxNTZjZjRlNzUxMjZlYzc3ODAxMWViNmIyNzhmMmYyMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.p8mu3Euiznqf74SrbaIdAjgjFovTXMm7tqtyGCiu5HM)

**Comment by InfinityPacer** [comment]
关闭站点顺序刷流
