### ISSUE TITLE
站点刷流配置海胆后，不下载种子

### ISSUE THREAD

**Issue by chenstarsQ** [InfinityPacer/MoviePilot-Plugins#51]
站点刷流插件，配置海胆进行刷流，不下载种子，其他站都正常
<img width="947" alt="Snipaste_2024-10-06_09-42-04" src="https://github.com/user-attachments/assets/fb0efd31-0d75-4516-a470-67175aedf351">
INFO】2024-10-06 09:41:25,025 - brushflow - 刷流下载任务检查完成
【INFO】2024-10-06 09:41:24,607 - brushflow - 刷流任务统计数据，总任务数：536，活跃任务数：5，已删除：531，待归档：397，活跃上传量：16.92G，活跃下载量：76.1G，总上传量：1.81T，总下载量：6.38T
【INFO】2024-10-06 09:41:24,554 - brushflow - 自动归档记录天数小于等于0，取消自动归档
【INFO】2024-10-06 09:41:24,505 - brushflow - 没有开启动态删种，按用户设置删种条件开始检查任务
【INFO】2024-10-06 09:41:24,492 - brushflow - 没有配置有效的排除标签，所有种子均参与后续处理
【INFO】2024-10-06 09:41:24,484 - brushflow - 当前刷流任务共 5 个有效种子，正在准备按设定的种子标签进行排除
【INFO】2024-10-06 09:41:24,474 - brushflow - 已开启下载器监控，开始同步刷流任务删除记录
【INFO】2024-10-06 09:41:24,460 - brushflow - 共有 402 个任务正在刷流，开始检查任务状态
【INFO】2024-10-06 09:41:24,385 - brushflow - 已开启下载器监控，开始同步种子刷流标签记录
【INFO】2024-10-06 09:41:24,291 - brushflow - 开始检查刷流下载任务 ...
【INFO】2024-10-06 09:41:24,266 - brushflow - 刷流任务执行完成
【INFO】2024-10-06 09:41:24,155 - brushflow - 站点 海胆之家 刷流完成
【INFO】2024-10-06 09:41:13,233 - brushflow - 正在准备种子刷流，数量 257
【INFO】2024-10-06 09:41:13,213 - brushflow - 开始获取站点 海胆之家 的新种子 ...
【INFO】2024-10-06 09:41:13,180 - brushflow - 没有开启排除订阅，取消订阅标题匹配
【INFO】2024-10-06 09:41:13,149 - brushflow - 即将针对站点 海胆之家 开始刷流
【INFO】2024-10-06 09:41:12,964 - brushflow - 开始执行刷流任务 ...
【INFO】2024-10-06 09:41:10,364 - brushflow - 站点刷流Check定时服务启动，时间间隔 5 分钟
【INFO】2024-10-06 09:41:10,320 - brushflow - 站点刷流Brush定时服务启动，时间间隔 10 分钟
【INFO】2024-10-06 09:41:09,953 - brushflow - 站点刷流Check服务启动，立即运行一次
【INFO】2024-10-06 09:41:09,888 - brushflow - 站点刷流Brush服务启动，立即运行一次
【INFO】2024-10-06 09:41:01,607 - brushflow - 站点刷流Check定时服务启动，时间间隔 5 分钟
【INFO】2024-10-06 09:41:01,550 - brushflow - 站点刷流Brush定时服务启动，时间间隔 10 分钟

**Comment by InfinityPacer** [comment]
查看README排查

**Comment by QiHang-78** [comment]
同问题，是否有解决？
