### ISSUE TITLE
关于刷流保种时间和多站点独立配置的冲突

### ISSUE THREAD

**Issue by ignimutos** [InfinityPacer/MoviePilot-Plugins#53]
[插件名称]:
站点刷流 

[插件版本]:
v3.8

[问题描述]: 
首先我对种子进行了辅种，在下载器中生成了多个种子对应一个下载文件，若此时刷流判断其中一个站点的保种时间满足了条件，会将此种子及对应的文件均删除，会出现多个种子进度归0的情况

[解决思路]:
需对辅种的情况进行额外判断，有两种解决方案或者说两种策略以供选择：
1.取最长的保种时间进行判断
2.以分类/标签进行判断，也就是以原始种对应站点的保种时间进行判断(需要在辅种插件中选择为辅种增加分类/标签)

[额外问题]
这个问题因为刷流规则问题难以复现，我猜测很有可能存在，也是同一个种子的情况，在刷流时不同站点可能新增了两个完全相同的下载任务。当时检查任务的时候就发现了然后删除掉了多余的任务，复查的时候发现第二个站点同名的种子有两个，有一个是和第一个站点的同名种子完全一样，不太确定是否为同一个种子进行了刷流。
因为我是新入坑PT，不知道是否有考核下载量的站点。若这个问题属实，插件需要提供一个额外配置以供选择

**Comment by ignimutos** [comment]
不知道为什么提交issue后丢失了一部分写的内容，我重新写一下
### 插件名称
站点刷流

### 插件版本
v3.8

### 问题描述
假设我有个种子A，对其进行了辅种，生成了B，C两个种子。对应的站点也分别称为A，B，C应该方便理解，这三个站点的保种时间设置分别为10，20，30小时。
站点刷流插件触发站点A的保种时间删除规则，对其进行了删除，此时会将种子及文件同时删除。

### 解决思路
1. 取最长的保种时间进行判断
2. 以分类/标签进行判断，也就是以原始种对应站点的保种时间进行判断(需要在辅种插件中选择为辅种增加分类/标签)

### 额外问题
这个问题因为刷流规则问题难以复现，我猜测很有可能存在，也是同一个种子的情况，在刷流时不同站点可能新增了两个完全相同的下载任务。当时检查任务的时候就发现了然后删除掉了多余的任务，复查的时候发现第二个站点同名的种子有两个，有一个是和第一个站点的同名种子完全一样，不太确定是否为同一个种子进行了刷流。
因为我是新入坑PT，不知道是否有考核下载量的站点。若这个问题属实，插件需要提供一个额外配置以供选择

**Comment by InfinityPacer** [comment]
同一种子在多站同时做种，的确可能出现类似的问题，这是已知问题，在v2插件中有未来的开发计划

**Comment by aicenluo** [comment]
接着题主的思路，补充一个我遇到的问题：当刷流插件删除了A种子后，因为辅种的B，C两个种子还在，但是文件其实已经被删除了，这个时候，qb又会重新下载这个文件，导致存在一个问题：有可能该种子在B，C对应的站点已经不是free状态了，重复在下载的话反而增加了这两个站点的下载量，分享率也下降了。
我尝试用变通的办法解决这个问题，用自动删种插件，判断种子状态，自动删除已经丢失文件的种子任务，这个办法不能完全解决问题。所以我认为最根本的解决方法还是在辅种插件：辅种插件增加联动删除功能，即检测到A源文件删除以后，自动删除B，C的辅种任务和文件。

**Comment by InfinityPacer** [comment]
刷流就不要辅种了，就算刷流后续支持，也是支持刷流插件自己刷到的辅种种子
