### ISSUE TITLE
添加刷流任务报错expected value (list, dict, int or string) in bencoded string [bdecode:4]”

### ISSUE THREAD

**Issue by cxfuxi** [InfinityPacer/MoviePilot-Plugins#54]
qb版本：qBittorrent v5.0.0 WebUI (64-bit)
刷流插件版本：v3.8
MP版本：v1.9.17
qb报错
{
    "id": 380,
    "message": "正在下载 Torrent... 来源：“https://zmpt.cc/download.php?id=62931”",
    "timestamp": 1729588465,
    "type": 1
  },
  {
    "id": 381,
    "message": "添加 Torrent 失败。来源：“https://zmpt.cc/download.php?id=62931”。原因：“expected value (list, dict, int or string) in bencoded string [bdecode:4]”",
    "timestamp": 1729588466,
    "type": 4
  },
  {
    "id": 382,
    "message": "正在下载 Torrent... 来源：“https://zmpt.cc/download.php?id=62930”",
    "timestamp": 1729588493,
    "type": 1
  },
  {
    "id": 383,
    "message": "添加 Torrent 失败。来源：“https://zmpt.cc/download.php?id=62930”。原因：“expected value (list, dict, int or string) in bencoded string [bdecode:4]”",
    "timestamp": 1729588493,
    "type": 4
  }

插件日志报错

【WARNING】2024-10-22 17:26:53,458 - brushflow - Pinocchio 1940 1080p KKTV WEB-DL AVC AAC-ZmWeb 添加刷流任务失败！
【ERROR】2024-10-22 17:26:53,456 - brushflow - qbittorrent 获取种子Hash失败，详细信息请查看 README
【WARNING】2024-10-22 17:26:26,060 - brushflow - The Grapes of Wrath 1940 1080p KKTV WEB-DL AVC AAC-ZmWeb 添加刷流任务失败！
【ERROR】2024-10-22 17:26:26,058 - brushflow - qbittorrent 获取种子Hash失败，详细信息请查看 README
【WARNING】2024-10-22 17:25:58,639 - brushflow - Carved 2024 2160p HULU WEB-DL DD+5.1 H.265-playWEB 添加刷流任务失败！
【ERROR】2024-10-22 17:25:58,637 - brushflow - qbittorrent 获取种子Hash失败，详细信息请查看 README
【WARNING】2024-10-22 17:25:31,246 - brushflow - Drova Update v1.02 NSW-VENOM 添加刷流任务失败！
【ERROR】2024-10-22 17:25:31,244 - brushflow - qbittorrent 获取种子Hash失败，详细信息请查看 README
【WARNING】2024-10-22 17:25:03,831 - brushflow - Forest Evolutionism S02E03 2024 1080p WEB-DL H265 AAC-ADWeb 添加刷流任务失败！
【ERROR】2024-10-22 17:25:03,830 - brushflow - qbittorrent 获取种子Hash失败，详细信息请查看 README
【WARNING】2024-10-22 17:24:36,415 - brushflow - Forest Evolutionism S02E04 2024 1080p WEB-DL H265 AAC-ADWeb 添加刷流任务失败！
【ERROR】2024-10-22 17:24:36,413 - brushflow - qbittorrent 获取种子Hash失败，详细信息请查看 README
【WARNING】2024-10-22 17:24:08,997 - brushflow - Forest Evolutionism S02E03 2024 2160p WEB-DL H265 AAC-ADWeb 添加刷流任务失败！
【ERROR】2024-10-22 17:24:08,995 - brushflow - qbittorrent 获取种子Hash失败，详细信息请查看 README
【WARNING】2024-10-22 17:23:41,576 - brushflow - Forest Evolutionism S02E04 2024 2160p WEB-DL H265 AAC-ADWeb 添加刷流任务失败！

**Comment by cxfuxi** [comment]
已解决，站点不支持5.x的qb，降级后恢复正常

**Comment by wcxxxxx** [comment]
> 已解决，站点不支持5.x的qb，降级后恢复正常

降低到多少了呀

**Comment by cxfuxi** [comment]
> > 已解决，站点不支持5.x的qb，降级后恢复正常
> 
> 降低到多少了呀

上你挂的网站看，上面一般要写
