### ISSUE TITLE
关于2.0版刷流插件qb下不会自动添加分类的问题

### ISSUE THREAD

**Issue by aicenluo** [InfinityPacer/MoviePilot-Plugins#55]
我现在用2.0的刷流插件配合qb刷流，在添加新任务以后，不会自动添加分类了，之前1.0版，同样的设置，会成功添加分类。
标签添加功能正常。
![image](https://github.com/user-attachments/assets/9327ddbe-91a0-416d-bf93-c1771dc8757b)
![image](https://github.com/user-attachments/assets/67c71daa-5b90-4e2d-adea-dffc1337be74)

**Comment by InfinityPacer** [comment]
下载器开启自动分类

**Comment by aicenluo** [comment]
下载器开启自动分类以后，目录和分类都被下载器接管了。实际上正常的添加分类动作应该是刷流插件自动添加的，比如mp1.0的刷流插件，在添加刷流任务的时候，会自动在qb的分类上添加我设置好的种子分类，比如“刷流”，但是现在我用的mp2.0中的刷流插件，配合下载器管理插件，可以成功添加标签，但是不会自动添加设置好的“刷流”分类（见图）。基本上可以确定是插件的bug，不论是官方版的还是低频版的都用这个问题。虽然不影响刷流的主要功能，但是确实是个小问题，还请大佬有空查看一下。谢谢！
![image](https://github.com/user-attachments/assets/d40df925-c7fd-416d-9c6c-2323447610a1)
![image](https://github.com/user-attachments/assets/3d4a4ff7-90b2-4f65-947f-09796c44c260)

**Comment by InfinityPacer** [comment]
请开启下载器自动分类，谢谢

**Comment by aicenluo** [comment]
你指的是这个位置的“自动分类管理”吗？
