### ISSUE TITLE
总上传带宽的问题

### ISSUE THREAD

**Issue by LoSiTeE** [InfinityPacer/MoviePilot-Plugins#6]
记得以前老的插件里面的逻辑是：总上传带宽设置的值大于TR+QB的上传速度之和，就继续拉种子。

目前插件版本2.8，上传速度TR是6MB/s，QB是1MB/s，设置的总上传带宽为4000KB/s，但是插件依然会拉刷流种子。简单查看了下插件日志，好像现在只会统计所选择下载器的上传带宽作为比较数值了。因为我选择了QB，所以TR的上传速度将不做计算。

请问可以修改回以前的逻辑吗？
这样的话对保种党比较友好，既可以以TR的保种为上传主力，同时如果TR的保种速度相对下降，也可以补充一些刷流种子进QB。感觉这样会比较好一些。

**Comment by InfinityPacer** [comment]
下版优化
