### ISSUE TITLE
站点刷流插件中，当分享率过低时，下载种子会发生302重定向的问题

### ISSUE THREAD

**Issue by AtmosphereMao** [InfinityPacer/MoviePilot-Plugins#60]
插件：站点刷流（低频版）
站点：https://pt.btschool.club/

插件日志：
![image](https://github.com/user-attachments/assets/2851d995-9c74-478a-a31b-08496df2a748)

qBittorrent发生以下错误：
![image](https://github.com/user-attachments/assets/1f6132c3-8bfb-4d1f-8ede-0bfbc0df15a9)

通过浏览器访问该torrent URL：
![image](https://github.com/user-attachments/assets/5dc8db22-2425-404d-bb99-c9c5833c54d0)
因**分享率不足**会被重定向到警告页面中了，无法正确获取种子

![image](https://github.com/user-attachments/assets/a12a78cc-9893-48f1-bb9a-09f9011c4a73)

torrent URL添加Query参数letdown=1即可忽视警告

**Comment by InfinityPacer** [comment]
aacb83e8476702c08022cf8fd606b6355dad7611
