### ISSUE TITLE
Webdav备份 MPv2 备份到alist报错

### ISSUE THREAD

**Issue by jayvzh** [InfinityPacer/MoviePilot-Plugins#62]
【ERROR】2024-11-29 09:57:13,249 - webdavbackup - 上传到WebDAV服务器失败: Method 'check' not supported for http://xxx
![微信截图_20241129100846](https://github.com/user-attachments/assets/9651a67f-b46f-4acb-b5fb-afdc4728218a)

**Comment by InfinityPacer** [comment]
关闭校验
