### ISSUE TITLE
刷流插件 4.0 下载超时删除规则会将已经下载完成的种子删除

### ISSUE THREAD

**Issue by lengyu-lys** [InfinityPacer/MoviePilot-Plugins#65]
qb 中有一个种子是手动添加下载的，下载完成后，通过手动增加 刷流标签加入刷流插件进行管理。种子下载完成时间是36h，设置的下载超时时间是 24 小时，就会出现插件将已经下载完成的种子删除掉的情况。请问这是预期的吗？我理解下载超时这条规则应该只对还未下载完成的种子生效？

**Comment by InfinityPacer** [comment]
辅种不建议纳入刷流管理，正常种子未能重现。
