### ISSUE TITLE
刷流插件 4.0 保种体积统计并非实际磁盘占用

### ISSUE THREAD

**Issue by lengyu-lys** [InfinityPacer/MoviePilot-Plugins#67]
通过日志和文件系统对比，发现现在刷流插件统计保种体积是采用 种子中文件大小，而非实际磁盘占用大小，如果未完成全部下载，会导致体积统计不准，从而删除不必要的种子。

举例来说，如果有个种子体积是 1T，实际只下载了 100G，但是当刷流插件进行体积检查时，得到的做种体积是 1T 而非 100G，如果设置的保种体积为 500G的话此时会误判导致不再新增下载，如果设置了自动删除，则会立即启用自动删除，导致非预期的删种

**Comment by InfinityPacer** [comment]
设计如此
