### ISSUE TITLE
自动诊断V1.1所需版本与主程序版本不匹配

### ISSUE THREAD

**Issue by behinder85** [InfinityPacer/MoviePilot-Plugins#7]
![image](https://github.com/InfinityPacer/MoviePilot-Plugins/assets/60542924/4bba7a31-6e71-42b2-b813-0f006da17cb8)

如图，需主程序V1.9.3以上，但目前主程序更新至V1.9.2
故而此版本插件无法使用（开个issue，提醒一下后面想用的小伙伴们）

**Comment by InfinityPacer** [comment]
1.9.3+已发布
