### ISSUE TITLE
WEBEAV插件同步失败

### ISSUE THREAD

**Issue by sebowang** [InfinityPacer/MoviePilot-Plugins#70]
采用坚果云进行备份，发现不能备份成功，日志如下
![image](https://github.com/user-attachments/assets/8979d05a-a660-4c46-b496-728fe7da0b50)

【INFO】2024-12-14 13:50:48,353 - webdavbackup - 备份失败，请排查日志
【INFO】2024-12-14 13:50:48,350 - webdavbackup - 清理本地临时文件：/config/MoviePilot-Backup-2024-12-14_13-50-47.zip
【ERROR】2024-12-14 13:50:48,347 - webdavbackup - 上传到WebDAV服务器失败: Remote parent for: /MoviePilot-Backup-2024-12-14_13-50-47.zip not found
【INFO】2024-12-14 13:50:48,023 - webdavbackup - 远程备份路径为：https://dav.jianguoyun.com/dav/MoviePilot-Backup-2024-12-14_13-50-47.zip
【INFO】2024-12-14 13:50:48,022 - webdavbackup - 清理本地临时文件夹：/config/MoviePilot-Backup-2024-12-14_13-50-47
【INFO】2024-12-14 13:50:48,020 - webdavbackup - 成功创建ZIP备份文件: /config/MoviePilot-Backup-2024-12-14_13-50-47.zip
【INFO】2024-12-14 13:50:47,938 - webdavbackup - 正在压缩备份文件: /config/MoviePilot-Backup-2024-12-14_13-50-47.zip
【INFO】2024-12-14 13:50:47,937 - webdavbackup - 正在备份文件: /config/category.yaml
【INFO】2024-12-14 13:50:47,934 - webdavbackup - 正在备份文件: /config/app.env
【INFO】2024-12-14 13:50:47,932 - webdavbackup - 正在备份目录: /config/cookies
【INFO】2024-12-14 13:50:47,930 - webdavbackup - 正在备份文件: /config/user.db
【INFO】2024-12-14 13:50:47,885 - webdavbackup - 本地临时备份文件夹路径：/config/MoviePilot-Backup-2024-12-14_13-50-47
【INFO】2024-12-14 13:50:47,883 - webdavbackup - 成功连接到WebDAV服务器
【INFO】2024-12-14 13:50:47,693 - webdavbackup - 开始执行WebDAV备份
【INFO】2024-12-14 13:50:44,702 - webdavbackup - WebDAV备份定时服务已开启，时间间隔 0 8 * * 5 
【INFO】2024-12-14 13:50:44,689 - webdavbackup - WebDAV备份服务，立即运行一次
【INFO】2024-12-14 13:47:48,889 - webdavbackup - 备份失败，请排查日志

**Comment by InfinityPacer** [comment]
请查看插件说明
