### ISSUE TITLE
自动归档天数是什么作用

### ISSUE THREAD

**Issue by littlefisher666** [InfinityPacer/MoviePilot-Plugins#71]
我配置了1500G的保种体积，可实际下载量完全达不到，但是看日志却说已经达到保种体积了的，我怀疑是不是这个自动归档天数导致已经删除的种子还被计算了体积的

**Comment by InfinityPacer** [comment]
https://github.com/InfinityPacer/MoviePilot-Plugins/blob/main/plugins.v2/brushflowlowfreq/README.md
