### ISSUE TITLE
plex优选ip插件编码问题

### ISSUE THREAD

**Issue by Laeoo** [InfinityPacer/MoviePilot-Plugins#74]
【INFO】2024-12-27 11:41:34,867 - plexspeedtest - Hosts写入完成
【INFO】2024-12-27 11:41:34,845 - plexspeedtest - 已完成插件热加载: CustomHosts
【INFO】2024-12-27 11:41:34,822 - plexspeedtest - 成功热加载插件到插件服务: CustomHosts
【INFO】2024-12-27 11:41:34,805 - plexspeedtest - 成功热加载插件: CustomHosts 到内存

UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    hosts_entries = [line for line in hosts_file]
  File "C:\Windows-MoviePilot-Git\Python3.11\Lib\site-packages\python_hosts\hosts.py", line 488, in <listcomp>
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    hosts_entries = [line for line in hosts_file]
  File "C:\Windows-MoviePilot-Git\Python3.11\Lib\site-packages\python_hosts\hosts.py", line 488, in populate_entries
    self.populate_entries()
  File "C:\Windows-MoviePilot-Git\Python3.11\Lib\site-packages\python_hosts\hosts.py", line 161, in __init__
           ^^^^^^^^^^^^^^^^^^^^^^
    return Hosts(path=hosts_path)
  File "C:\Windows-MoviePilot-Git\MoviePilot\app\plugins\customhosts\__init__.py", line 194, in __read_system_hosts
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
    system_hosts = self.__read_system_hosts()
  File "C:\Windows-MoviePilot-Git\MoviePilot\app\plugins\customhosts\__init__.py", line 222, in __add_hosts_to_system
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    error_flag, error_hosts = self.__add_hosts_to_system(self._hosts)
  File "C:\Windows-MoviePilot-Git\MoviePilot\app\plugins\customhosts\__init__.py", line 53, in init_plugin
    plugin_obj.init_plugin(self.get_plugin_config(plugin_id))
  File "C:\Windows-MoviePilot-Git\MoviePilot\app\core\plugin.py", line 180, in start
【ERROR】2024-12-27 11:41:34,790 - plugin.py - 加载插件 CustomHosts 出错：'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence - Traceback (most recent call last):
【INFO】2024-12-27 11:41:34,743 - plugin.py - 插件停止完成
【INFO】2024-12-27 11:41:34,730 - plugin.py - 正在停止插件 CustomHosts...
【INFO】2024-12-27 11:41:34,719 - plexspeedtest - 准备热加载插件: CustomHosts
【INFO】2024-12-27 11:41:34,683 - plexspeedtest - Plex DNS 记录: [{'Hostname': 'app-qa.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'meta.plex.tv', 'IP Address': '104.18.27.211'}, {'Hostname': 'chapterdb.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'static.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'metadata-static.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'website-static.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'provider-static.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'bundle-archive-codeload.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'acoustid.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'lyricfind.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'analytics-stage.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'chapterdb-archive.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'bundle-archive.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'watch-staging.plex.tv', 'IP Address': '104.18.27.211'}, {'Hostname': 'images-staging.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'sonos-staging.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'gist-staging.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'blog.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'watch.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'songkick.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'email.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'mpm.plex.tv', 'IP Address': '104.18.26.211'}, {'Hostname': 'help.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'plexamp.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'ump.plex.tv', 'IP Address': '104.18.26.211'}, {'Hostname': 'app.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'metadata.provider.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'music.provider.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'vod.provider.plex.tv', 'IP Address': '104.18.27.211'}, {'Hostname': 'music-staging.provider.plex.tv', 'IP Address': '104.18.26.211'}, {'Hostname': 'epg-staging.provider.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'email-staging.provider.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'discover-staging.provider.plex.tv', 'IP Address': '104.18.27.211'}, {'Hostname': 'play-staging.provider.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'epg.provider.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'email.provider.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'discover.provider.plex.tv', 'IP Address': '104.18.26.211'}, {'Hostname': 'vod2-dev.provider.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'legadata-dev.provider.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'metadata-dev.provider.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'music-dev.provider.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'vod-dev.provider.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'datadog-dev.provider.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'epg-dev.provider.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'discover-dev.provider.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'news-dev.provider.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'play-dev.provider.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'play.provider.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'transcoder.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'cordcutter.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'staging1-cordcutter.plex.tv', 'IP Address': '104.18.27.211'}, {'Hostname': 'staging3-cordcutter.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'ump-paas.plex.tv', 'IP Address': '104.18.26.211'}, {'Hostname': 'analytics.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'downloads.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'images.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'nightlies.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'scrobbles.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'links.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'plugins.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'sonos.plex.tv', 'IP Address': '104.18.27.211'}, {'Hostname': 'htbackdrops.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'artifacts.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'assets.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'clients.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'support.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'staging1-support.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'staging3-support.plex.tv', 'IP Address': '104.18.27.211'}, {'Hostname': 'gist.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'images-dev.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'sonos-dev.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'www.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'staging1-www.plex.tv', 'IP Address': '104.18.27.211'}, {'Hostname': 'staging3-www.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'mbz.plex.tv', 'IP Address': '172.64.146.103'}]
【INFO】2024-12-27 11:41:34,665 - plexspeedtest - 正在准备写入Hosts
【INFO】2024-12-27 11:41:34,641 - plexspeedtest - CloudflareSpeedTest配置中没有找到IP，将使用DNS记录中的IP
【WARNING】2024-12-27 11:41:34,622 - plexspeedtest - 没有获取在线 Plex DNS 记录，使用默认 DNS 记录
【ERROR】2024-12-27 11:41:34,607 - plexspeedtest - An unexpected error occurred while loading the file: Bad offset for central directory
【INFO】2024-12-27 11:41:34,523 - plexspeedtest - 开始执行Plex IP优选服务
【INFO】2024-12-27 11:39:20,672 - plexspeedtest - 以下插件尚未安装: 自定义Hosts
【INFO】2024-12-27 11:39:20,621 - plexspeedtest - 开始执行Plex IP优选服务

**Comment by Laeoo** [comment]
【INFO】2024-12-27 11:41:34,867 - plexspeedtest - Hosts写入完成
【INFO】2024-12-27 11:41:34,845 - plexspeedtest - 已完成插件热加载: CustomHosts
【INFO】2024-12-27 11:41:34,822 - plexspeedtest - 成功热加载插件到插件服务: CustomHosts
【INFO】2024-12-27 11:41:34,805 - plexspeedtest - 成功热加载插件: CustomHosts 到内存

UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    hosts_entries = [line for line in hosts_file]
  File "C:\Windows-MoviePilot-Git\Python3.11\Lib\site-packages\python_hosts\hosts.py", line 488, in <listcomp>
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    hosts_entries = [line for line in hosts_file]
  File "C:\Windows-MoviePilot-Git\Python3.11\Lib\site-packages\python_hosts\hosts.py", line 488, in populate_entries
    self.populate_entries()
  File "C:\Windows-MoviePilot-Git\Python3.11\Lib\site-packages\python_hosts\hosts.py", line 161, in __init__
           ^^^^^^^^^^^^^^^^^^^^^^
    return Hosts(path=hosts_path)
  File "C:\Windows-MoviePilot-Git\MoviePilot\app\plugins\customhosts\__init__.py", line 194, in __read_system_hosts
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
    system_hosts = self.__read_system_hosts()
  File "C:\Windows-MoviePilot-Git\MoviePilot\app\plugins\customhosts\__init__.py", line 222, in __add_hosts_to_system
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    error_flag, error_hosts = self.__add_hosts_to_system(self._hosts)
  File "C:\Windows-MoviePilot-Git\MoviePilot\app\plugins\customhosts\__init__.py", line 53, in init_plugin
    plugin_obj.init_plugin(self.get_plugin_config(plugin_id))
  File "C:\Windows-MoviePilot-Git\MoviePilot\app\core\plugin.py", line 180, in start
【ERROR】2024-12-27 11:41:34,790 - plugin.py - 加载插件 CustomHosts 出错：'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence - Traceback (most recent call last):
【INFO】2024-12-27 11:41:34,743 - plugin.py - 插件停止完成
【INFO】2024-12-27 11:41:34,730 - plugin.py - 正在停止插件 CustomHosts...
【INFO】2024-12-27 11:41:34,719 - plexspeedtest - 准备热加载插件: CustomHosts
【INFO】2024-12-27 11:41:34,683 - plexspeedtest - Plex DNS 记录: [{'Hostname': 'app-qa.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'meta.plex.tv', 'IP Address': '104.18.27.211'}, {'Hostname': 'chapterdb.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'static.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'metadata-static.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'website-static.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'provider-static.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'bundle-archive-codeload.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'acoustid.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'lyricfind.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'analytics-stage.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'chapterdb-archive.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'bundle-archive.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'watch-staging.plex.tv', 'IP Address': '104.18.27.211'}, {'Hostname': 'images-staging.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'sonos-staging.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'gist-staging.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'blog.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'watch.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'songkick.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'email.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'mpm.plex.tv', 'IP Address': '104.18.26.211'}, {'Hostname': 'help.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'plexamp.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'ump.plex.tv', 'IP Address': '104.18.26.211'}, {'Hostname': 'app.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'metadata.provider.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'music.provider.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'vod.provider.plex.tv', 'IP Address': '104.18.27.211'}, {'Hostname': 'music-staging.provider.plex.tv', 'IP Address': '104.18.26.211'}, {'Hostname': 'epg-staging.provider.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'email-staging.provider.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'discover-staging.provider.plex.tv', 'IP Address': '104.18.27.211'}, {'Hostname': 'play-staging.provider.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'epg.provider.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'email.provider.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'discover.provider.plex.tv', 'IP Address': '104.18.26.211'}, {'Hostname': 'vod2-dev.provider.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'legadata-dev.provider.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'metadata-dev.provider.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'music-dev.provider.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'vod-dev.provider.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'datadog-dev.provider.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'epg-dev.provider.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'discover-dev.provider.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'news-dev.provider.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'play-dev.provider.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'play.provider.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'transcoder.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'cordcutter.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'staging1-cordcutter.plex.tv', 'IP Address': '104.18.27.211'}, {'Hostname': 'staging3-cordcutter.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'ump-paas.plex.tv', 'IP Address': '104.18.26.211'}, {'Hostname': 'analytics.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'downloads.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'images.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'nightlies.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'scrobbles.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'links.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'plugins.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'sonos.plex.tv', 'IP Address': '104.18.27.211'}, {'Hostname': 'htbackdrops.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'artifacts.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'assets.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'clients.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'support.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'staging1-support.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'staging3-support.plex.tv', 'IP Address': '104.18.27.211'}, {'Hostname': 'gist.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'images-dev.plex.tv', 'IP Address': '172.64.146.103'}, {'Hostname': 'sonos-dev.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'www.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'staging1-www.plex.tv', 'IP Address': '104.18.27.211'}, {'Hostname': 'staging3-www.plex.tv', 'IP Address': '104.18.41.153'}, {'Hostname': 'mbz.plex.tv', 'IP Address': '172.64.146.103'}]
【INFO】2024-12-27 11:41:34,665 - plexspeedtest - 正在准备写入Hosts
【INFO】2024-12-27 11:41:34,641 - plexspeedtest - CloudflareSpeedTest配置中没有找到IP，将使用DNS记录中的IP
【WARNING】2024-12-27 11:41:34,622 - plexspeedtest - 没有获取在线 Plex DNS 记录，使用默认 DNS 记录
【ERROR】2024-12-27 11:41:34,607 - plexspeedtest - An unexpected error occurred while loading the file: Bad offset for central directory
【INFO】2024-12-27 11:41:34,523 - plexspeedtest - 开始执行Plex IP优选服务
【INFO】2024-12-27 11:39:20,672 - plexspeedtest - 以下插件尚未安装: 自定义Hosts
【INFO】2024-12-27 11:39:20,621 - plexspeedtest - 开始执行Plex IP优选服务

**Comment by InfinityPacer** [comment]
Windows 需手工修改系统 hosts 文件为 UTF-8 编码，否则自定义 Hosts 插件不适用于 Windows
